version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update npm
          command: |
            sudo npm i -g npm
      - run:
          name: Installing npm dependencies
          command: |
            sudo npm install -g
      - run:
          name: Installed npm dependencies successfully
          command: |
            echo "Installed npm dependencies"
      - run:
          name: Installing firebase-tools
          command: |
            sudo npm install -g firebase-tools
      - run:
          name: Installed firebase-tools  successfully
          command: |
            ls -al
            echo "Installed firebase-tools"
      - save_cache:
          key: v1-ecommerceWepsite-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Installed firebase-tools  successfully
          command: |
            ls -al
            echo "done installing dependencies"
          

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Running build
          command: |
            ls -al
            sudo npm run build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploying
          command: |
            ls -al
            firebase deploy --token $FIREBASE_TOKEN

workflows:
  build_process:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
