const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "Sign_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",

  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERRORS: "SIGN_UP_ERRORS",
  SIGN_IN_ERRORS: "SIGN_IN_ERRORS",
  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_ERRORS: "RESET_PASSWORD_ERRORS",
  RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
};

export default userTypes;
